add vscode settings, update bspwm config

diff --git a/bspwm/scripts/Unsplash b/bspwm/scripts/Unsplash
--- a/bspwm/scripts/Unsplash
+++ b/bspwm/scripts/Unsplash
@@ -2,26 +2,23 @@
 
 img_dir=~/Pictures/wallpapers
 resolution="1920x1080"
-image_url="https://source.unsplash.com/featured/${resolution}/?tokyo,pixel"
+image_url="https://source.unsplash.com/featured/${resolution}/?tokyo,night,dark"
 current_time=$(date +"%Y-%m-%d_%H-%M-%S")
 
 if [ ! -d "$img_dir" ]; then
-	mkdir $img_dir
-	notify-send "Directory $img_dir created."
+    mkdir $img_dir
 fi
 
 if [ "$(ls -A $img_dir)" ]; then
-	notify-send "Cleaning up old images..."
-	find $img_dir -type f -mtime +1 -delete
+    find $img_dir -type f -mtime +1 -delete
 fi
 
 wget -q "$image_url" -O $img_dir/$current_time.jpg
 
 if [ -f $img_dir/$current_time.jpg ]; then
-	feh --bg-scale $img_dir/$current_time.jpg
-	notify-send "Change wallpaper image successfully!!!"
+    feh --bg-scale $img_dir/$current_time.jpg
+    echo "Changed wallpaper image successfully!"
 else
-	notify-send "Error: Image not downloaded!"
-	exit 1
+    echo "Error: Image not downloaded!"
+    exit 1
 fi
-
